#!/usr/bin/env python3
"""Regenerate the <link rel="apple-touch-startup-image"> block in index.html.

iOS does NOT use the manifest's background_color for a home-screen app's
launch screen. With no startup image it paints the launch screen WHITE, which
is the white flash reported on every launch, before the app's own splash gets
a chance to render. The only way to colour that screen is to hand iOS an
image for the exact device resolution, matched by media query - it ignores
anything whose dimensions do not match, and falls back to white.

Every image here is a flat SPLASH_COLOR, matching #splashscreen's own
background, so the launch screen and the splash are the same colour and the
handover between them is invisible. A solid-colour PNG is tiny (under a
kilobyte even at 1320x2868), so covering every device costs ~40KB of an
already 1.6MB file, and gzip collapses the repetition further.

Data URIs, not files, to keep the single-file deployment model - the same
thing apple-touch-icon already does successfully in this app.

    python3 tools/gen-startup-images.py          # rewrite index.html in place
    python3 tools/gen-startup-images.py --check   # report only, exit 1 if stale
"""
import argparse
import base64
import io
import os
import re
import sys

from PIL import Image

SPLASH_COLOR = (0x0A, 0x0A, 0x0A)
HERE = os.path.dirname(os.path.abspath(__file__))
INDEX = os.path.join(os.path.dirname(HERE), "index.html")
BEGIN = "<!-- BEGIN apple-touch-startup-image (generated by tools/gen-startup-images.py) -->"
END = "<!-- END apple-touch-startup-image -->"

# (css width, css height, device pixel ratio, what it covers)
DEVICES = [
    (320, 568, 2, "iPhone SE (1st gen), 5s"),
    (375, 667, 2, "iPhone 6/7/8, SE (2nd/3rd gen)"),
    (414, 736, 3, "iPhone 6/7/8 Plus"),
    (375, 812, 3, "iPhone X/XS, 11 Pro, 12/13 mini"),
    (414, 896, 2, "iPhone XR, 11"),
    (414, 896, 3, "iPhone XS Max, 11 Pro Max"),
    (390, 844, 3, "iPhone 12/12 Pro, 13/13 Pro, 14"),
    (428, 926, 3, "iPhone 12/13 Pro Max, 14 Plus"),
    (393, 852, 3, "iPhone 14 Pro, 15/15 Pro, 16"),
    (430, 932, 3, "iPhone 14 Pro Max, 15 Plus/Pro Max, 16 Plus"),
    (402, 874, 3, "iPhone 16 Pro"),
    (440, 956, 3, "iPhone 16 Pro Max"),
    (744, 1133, 2, "iPad mini (6th gen and later)"),
    (768, 1024, 2, "iPad mini (up to 5th gen), iPad 9.7\""),
    (810, 1080, 2, "iPad 10.2\""),
    (820, 1180, 2, "iPad Air 10.9\", iPad (10th gen)"),
    (834, 1112, 2, "iPad Pro 10.5\""),
    (834, 1194, 2, "iPad Pro 11\""),
    (834, 1210, 2, "iPad Air/Pro 11\" (M4)"),
    (1024, 1366, 2, "iPad Pro 12.9\""),
    (1032, 1376, 2, "iPad Pro 13\" (M4)"),
]


def png_data_uri(px_w, px_h):
    """A flat SPLASH_COLOR PNG, as small as PNG can express it."""
    im = Image.new("P", (px_w, px_h), 0)
    im.putpalette(list(SPLASH_COLOR) + [0] * (256 * 3 - 3))
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True, compress_level=9, bits=1)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def build_block():
    lines = [BEGIN,
             "<!-- Flat #%02X%02X%02X, the same colour as #splashscreen, so the launch" % SPLASH_COLOR,
             "     screen and the app's own splash are indistinguishable. Regenerate with",
             "     tools/gen-startup-images.py rather than editing by hand; iOS ignores any",
             "     image whose size does not match the device exactly and paints white",
             "     instead, which is the whole bug this exists to fix. -->"]
    total = 0
    for w, h, dpr, label in DEVICES:
        for orient, (pw, ph) in (("portrait", (w * dpr, h * dpr)),
                                 ("landscape", (h * dpr, w * dpr))):
            uri = png_data_uri(pw, ph)
            total += len(uri)
            lines.append(
                '<link rel="apple-touch-startup-image" '
                'media="screen and (device-width: {w}px) and (device-height: {h}px) '
                'and (-webkit-device-pixel-ratio: {d}) and (orientation: {o})" '
                'href="{u}"><!-- {lab} -->'.format(w=w, h=h, d=dpr, o=orient, u=uri, lab=label))
    lines.append(END)
    return "\n".join(lines), total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only; exit 1 if index.html is stale")
    args = ap.parse_args()

    block, total = build_block()
    src = io.open(INDEX, encoding="utf-8").read()

    if BEGIN in src:
        start = src.index(BEGIN)
        stop = src.index(END) + len(END)
        current = src[start:stop]
        if current == block:
            print("up to date (%d devices, %d link tags, %.0f KB of data URIs)"
                  % (len(DEVICES), len(DEVICES) * 2, total / 1024.0))
            return
        if args.check:
            print("STALE: the generated block does not match this script's output")
            sys.exit(1)
        src = src[:start] + block + src[stop:]
    else:
        if args.check:
            print("STALE: no generated block in index.html")
            sys.exit(1)
        anchor = '<link rel="manifest"'
        src = src.replace(anchor, block + "\n" + anchor, 1)

    io.open(INDEX, "w", encoding="utf-8").write(src)
    print("wrote %d link tags for %d devices (%.0f KB of data URIs)"
          % (len(DEVICES) * 2, len(DEVICES), total / 1024.0))


if __name__ == "__main__":
    main()
